// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIwOszz5XDR6S6urbzjBlBwf6L5Vi9fHk',
    appId: '1:304815957096:web:1910589de92f653b93c7dd',
    messagingSenderId: '304815957096',
    projectId: 'loginregister-d773c',
    authDomain: 'loginregister-d773c.firebaseapp.com',
    storageBucket: 'loginregister-d773c.appspot.com',
    measurementId: 'G-JK80FGS6ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAxzSIJNZXWIL_GHV10jOT3cjrRE9mKJo',
    appId: '1:304815957096:android:02842736c0dafb3293c7dd',
    messagingSenderId: '304815957096',
    projectId: 'loginregister-d773c',
    storageBucket: 'loginregister-d773c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4gXRFKlXphGlHcP9aPZPDpS5-5-2NWqo',
    appId: '1:304815957096:ios:3d1fbb31f1a0740693c7dd',
    messagingSenderId: '304815957096',
    projectId: 'loginregister-d773c',
    storageBucket: 'loginregister-d773c.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
